# Generated by Django 6.1.1 on 2026-09-08 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_padrao', models.DecimalField(decimal_places=2, help_text='Valor de referência cobrado normalmente por este serviço.', max_digits=8, verbose_name='Valor padrão')),
                ('ativo', models.BooleanField(default=True, help_text='Serviços inativos não aparecem para novos lançamentos.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, help_text='Valor efetivamente cobrado nesta execução (pode diferir do valor padrão).', max_digits=8, verbose_name='Valor cobrado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-data_hora'],
            },
        ),
    ]
